---
title: "Case_Study_EDA"
author: "Aurian Ghaemmaghami"
date: "2/22/2020"
output:
  html_document: default
  pdf_document: default
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

```{r}
options(max.print=10000)

##Introduction
#Hello and good afternoon. On behalf of the analytics team, we are pleased to present you our
#results and recommendations based on our analysis of the Beer & Brewery data. We will
#briefly be going over each of the questions in chronological order where we will provide
#our findings for each. Considering your schedules are very busy, our goal is to make sure
#this presentation is concise and to the point.

#Load in packages
library(ggplot2)
library(dplyr)
library(naniar)
library(stringr)
library(htmlwidgets)
library(class)
library(caret)
library(e1071)
library(maps)
library(mapproj)
library(openintro)
```

```{r}
#Read in Beers CSV
beer = read.csv(file.choose(), header=TRUE)

#Read in Breweries CSV
brew = read.csv(file.choose(), header=TRUE)
```

##Question 1
```{r}
#How many Breweries present in each state
brew %>%
  select(State)%>%
  ggplot(aes(x=reorder(State,State,function(x)-length(x)), fill = State))+
  geom_bar()+
  ggtitle("Total Number of Breweries in Each State")+
  xlab("Stat")+
  geom_text(stat='count', aes(label=..count..), vjust=-0.5)
```

##Question 2
```{r}
#Change brewery label so it matches beer df
names(brew)[1] = "Brewery_id"

#Change brewery IDs to factors
beer$Brewery_id = as.factor(beer$Brewery_id)
brew$Brewery_id = as.factor(brew$Brewery_id)

#Join DF by Brewery ID's and show top and bottom 6
df = inner_join(beer,brew, by = "Brewery_id")

#Print top 6 observations of merged beer data frames
head(df)

#Print bottom 6 observations of merged beer data frames
tail(df)
```

##Question 3
```{r}
#Check for NA's... we can see ABV and IBU have NA's only
#1005 Missing Values for IBU
#62 Missing Values for ABC
gg_miss_var(df)
ibuc = df %>% filter(!is.na(IBU))
abvc = df %>% filter(!is.na(ABV))
dim(df)[1] - dim(ibuc)[1]
dim(df)[1] - dim(abvc)[1]
```

##Question 4
```{r}
#Compute median ABV and IBU for reach state. Then compare with bar chart. Handle NA's
#DC and Kentucky have the highest Median ABV with 0.0625
#Maine has the highest Median IBU with 61.0

#Compute Median of ABV by State
df %>%
  filter(!is.na(ABV))%>%
  group_by(State)%>%
  summarize(MedianABV = median(ABV))%>%
  arrange(desc(MedianABV))%>%
  print(n=50)

#Compute Median of IBU by State
df %>%
  filter(!is.na(IBU))%>%
  group_by(State)%>%
  summarize(MedianIBU = median(IBU))%>%
  arrange(desc(MedianIBU))%>%
  print(n=50)

#Create bar chart of median ABV for each State
df %>%
  filter(!is.na(ABV))%>%
  group_by(State)%>%
  summarize(MedianABV = median(ABV))%>%
  ggplot(aes(x=reorder(State,-MedianABV), y = MedianABV, fill=State))+
  geom_bar(stat="identity")+
  xlab("State")+
  ggtitle("Bar Chart Distribution of Median ABV by State")
  
#Create bar chart of median IBU for each State
df %>%
  filter(!is.na(IBU))%>%
  group_by(State)%>%
  summarize(MedianIBU = median(IBU))%>%
  ggplot(aes(x=reorder(State,-MedianIBU), y = MedianIBU, fill=State))+
  geom_bar(stat="identity")+
  xlab("State")+
  ggtitle("Bar Chart Distribution of Median IBU by State")
```

##Question 5
```{r}
#Which state has the Highest ABV and IBU
#Highest ABV - Colorado, Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale @ 0.128ABV
#Highest IBU - Oregon, Oregon Bitter Bitch Imperial IPA @ 138IBU

#Scatter Plot to compute highest ABV
df %>%
  filter(!is.na(ABV))%>%
  group_by(State)%>%
  summarize(MaxABV = max(ABV))%>%
  ggplot(aes(x=reorder(State,-MaxABV), y = MaxABV, color=State))+
  geom_text(aes(label=State),hjust=0, vjust=0)+
  geom_point()+
  xlab("State")+
  ggtitle("Scatter Plot of Max ABV by State")+
  theme_gray()

#What value is the MAX ABV for Colorado?
coloradodf = df %>% filter(State == " CO")
coloradodf = coloradodf[order(coloradodf$ABV, decreasing=TRUE),]
head(coloradodf,1)

#Scatter Plot to compute highest IBU
df %>%
  filter(!is.na(IBU))%>%
  group_by(State)%>%
  summarize(MaxIBU = max(IBU))%>%
  ggplot(aes(x=reorder(State,-MaxIBU), y = MaxIBU, color=State))+
  geom_text(aes(label=State),hjust=0, vjust=0)+
  geom_point()+
  xlab("State")+
  ggtitle("Scatter Plot of Max IBU by State")+
  theme_gray()

#What value is the MAX IBU for Oregon?
oregondf = df %>% filter(State == " OR")
oregondf = oregondf[order(oregondf$IBU, decreasing=TRUE),]
head(oregondf,1)
```

##Question 6
```{r}
#Distribution of ABV variable
#Distribution looks slightly right skewed
df %>%
  filter(!is.na(ABV))%>%
  ggplot(aes(x=ABV))+
  geom_histogram(fill="mediumpurple2", col= "lightcyan3", size=1)+
  ggtitle("Distribution of ABV Variable")

#Summary stats of ABV variable
#Min ABV - 0.1%
#Q1 - 5%
#Median ABV - 5.6%
#Q3 - 6.7%
#Max ABV - 12.8%
#Average ABV - 6%
df%>%
  filter(!is.na(ABV))%>%
  summarize(MeanABV = mean(ABV), SDABV = sd(ABV), MedianABV = median(ABV), MaxABV = max(ABV), MinABV = min(ABV), Q1 = quantile(ABV,0.25), Q3 = quantile(ABV,0.75), Range = max(ABV)-min(ABV), count = n())
```

##Question 7
```{r}
#Relationship between ABV and IBV(Bitterness)?
#We can see a positive linear correlation with IBU and ABV.
#AS the bitterness is higher, the ABV usually increases as well.
#This makes sense since the higher percentage of alcohol will most
#likely make your drink more bitter
df %>%
  filter(!is.na(ABV) & !is.na(IBU))%>%
  ggplot(aes(x=IBU, y=ABV))+
  geom_point()+
  geom_smooth(method="lm", col = "blue")+
  ggtitle("Relationship between IBU and ABV")
```

##Question 8
```{r}
#KNN Classification of IPA or Ale based on IBU and ABV explanatory variables
beer_breweries_data1 = df %>% select(c(ABV, IBU, Style, Ounces))
beer_breweries_data1$IBU<-as.numeric(beer_breweries_data1$IBU)
str(beer_breweries_data1)

#The following code groups the beers by "IPA," "ALE," and "OTH."
beer_breweries_data1$BeerType <- ifelse(grepl("Ale$", beer_breweries_data1$Style, ignore.case = T), "ALE",
ifelse(grepl("IPA$", beer_breweries_data1$Style, ignore.case = T ), "IPA", "OTH"))

#Change BeerType to a factor and IBU/ABV to numeric
beer_breweries_data1$BeerType = as.factor(beer_breweries_data1$BeerType)
str(beer_breweries_data1)

#Selecting for only IPAs and ALEs.
beer_breweries_style = beer_breweries_data1 %>% filter(!is.na(BeerType) & !is.na(IBU) &!is.na(ABV)) %>%  
  filter(BeerType == "IPA" | BeerType == "ALE")
summary(beer_breweries_style)
beer_breweries_style = droplevels(beer_breweries_style, exclude = "OTH")
beer_breweries_style %>% ggplot(aes(x=IBU, y=ABV, color = BeerType)) + geom_point()
set.seed(101)
iterations = 200
numks = 100
splitPerc = .7
masterAcc = matrix(nrow = iterations, ncol = numks)
for(j in 1:iterations)
{
  beerIndices = sample(1:dim(beer_breweries_style)[1],round(splitPerc * dim(beer_breweries_style)[1]))
  train = beer_breweries_style[beerIndices,]
  test = beer_breweries_style[-beerIndices,]
  for(i in 1:numks)
  {
    classifications = knn(train[,c(1,2)],test[,c(1,2)],train$BeerType, prob = TRUE, k = i)
    table(classifications,test$BeerType)
    CM = confusionMatrix(table(classifications,test$BeerType))
    masterAcc[j,i] = CM$overall[1]
  }
  
}
MeanAcc = colMeans(masterAcc)
plot(seq(1,numks,1),MeanAcc, type = "l", xlab = "k", ylab = "Accuracy", main = "kNN Accuracy Model K 1-100")
which.max(MeanAcc)
max(MeanAcc)
## In the graph above, we can see how the accuracy of the model changes with the given number of data points, or "neighbors," taken into account. In the data output here you can see that the accuracy is almost 88% for k=43 .
```

##Question 8 cont...
```{r}
#NaiveBayes Approach
iterations = 200
masterAcc = matrix(nrow = iterations)
splitPerc = .7 #Training / Test split Percentage
for(j in 1:iterations)
{
  beerIndices = sample(1:dim(beer_breweries_style)[1],round(splitPerc * dim(beer_breweries_style)[1]))
  train = beer_breweries_style[beerIndices,]
  test = beer_breweries_style[-beerIndices,]
  
  model = naiveBayes(train[,c(1,2)],as.factor(train$BeerType))
  table(predict(model,test[,c(1,2)]),as.factor(test$BeerType))
  CM = confusionMatrix(table(predict(model,test[,c(1,2)]),as.factor(test$BeerType)))
  masterAcc[j] = CM$overall[1]
}
MeanAcc = colMeans(masterAcc)
MeanAcc

## We can see that this model achieved a mean accuracy of approximately 86.1%--not quite as high as the accuracy we achieved from using the k-NN model.
```

##Question 9
```{r}
#Find any useful inference from data
#We would like to test and see if there is a difference in ABV averages for IPA vs Other Ale's
#More specifically, tests to see if Ale or IPA differ in regards to ABV
#First we will use the AleIPA Data Frame address assumptions of normality and equal standard
#deviations prior to selecting the best test to administer for the question of interest above.

#Filter out Ale and IPA only
Aledf = df %>% filter(grepl("Ale",df$Style))
IPAdf = df %>% filter(grepl("IPA",df$Style))

#Create new DF
AleIPA = full_join(IPAdf,Aledf)
names(AleIPA)[1] = "Name"
names(AleIPA)[8] = "Brewery"

#Create new column of factors for Ale and IPA
Style_Type = c()
for(i in grepl("Ale",AleIPA$Style))
  {
  if(i == "TRUE")
    {
    Style_Type = c(Style_Type,"Ale")
    }else{
    Style_Type = c(Style_Type,"IPA")
    }
}

#Bind column to df
AleIPA = cbind(AleIPA,Style_Type)

#Turn Style_Type to factor
AleIPA$Style_Type = as.factor(AleIPA$Style_Type)

#Turn IBU to numeric
AleIPA$IBU = as.numeric(AleIPA$IBU)

#Check missing values
gg_miss_var(AleIPA)

#Filter them out to do training on data set
AleIPA = AleIPA %>% filter(!is.na(ABV) & !is.na(IBU))

#Check Histogram distribution for normality
AleIPA %>%
  select(Style_Type,ABV)%>%
  ggplot(aes(x=ABV, fill = Style_Type))+
  geom_histogram()+
  ggtitle("Histogram Distribution of ABV for Ale & IPA")+
  facet_wrap(~Style_Type)
  
#Check QQPlots for any departures from normality
qplot(sample=ABV, data=AleIPA, color=Style_Type)+
  xlab("Quantile")+
  ylab("ABV")+
  ggtitle("QQPlot Distribution of ABV of Ale vs IPA")

##Normality Assumption
#The histograms show relatively normal distribution with some evidence of right skewness from
#Ale diagram. The QQplots also show some departures from normality, but not enough to discredit
#the normality assumption. Nonetheless, we have a large enough sample size to assert normality.
#We will now move to visually validate the equal standard deviation assumption.

#Check Box plot distribution for equal standard deviations
AleIPA%>%
  select(Style_Type,ABV)%>%
  ggplot(aes(x=Style_Type, y=ABV, fill=Style_Type))+
  geom_boxplot()+
  ggtitle("Box Plot Distribution of ABV based on Ale vs IPA")+
  coord_flip()

#Check Dot plot distribution for equal standard deviations
AleIPA%>%
  select(Style_Type,ABV)%>%
  ggplot(aes(x=Style_Type, y=ABV, color=Style_Type))+
  geom_point()+
  ggtitle("Dot Plot Distribution of ABV based on Ale vs IPA")+
  coord_flip()

##Equal Standard Deviations Assumption
#After viewing the box plots of the spread, we can see a lot more variability in the Ale Beer
#type vs IPA. There is not enough visual evidence to suggest equal standard deviations. 
#We will move forward on testing with unequal standard deviations

#Welch's T-Test is the most powerful testing tool for these assumptions stated above.
#We will run a test to see if the mean ABV value is different between Ale vs IPA.
t.test(ABV~Style_Type, data = AleIPA, var.equal = FALSE)

#Conclusion
#The evidence suggests that the mean average of ABV between groups "Ale" and "IPA" are
#different. We can stronly assert that the IPA group has a larger mean ABV than Ale drinks.
#95% confidence interval will tell us there is [0.011,0.014] more ABV in IPA's vs Ale's. More
#specifically, IPA's hold about 1.1%-1.4% more ABV than other Ale's.
#Why is this important? This will allow the brewery company to assert the claim that their
#IPA's are stronger than other Ale's. They could then sell more IPA-based drinks in areas where higher ABV is preferred. Or they could target those areas whenever they are doing a new product launch of an IPA.

#Now we will create the logic for a heat map to see which states have highest average ABV
df$State = str_replace_all(df$State, fixed(" "), "")
stateabb = c()
for(i in df$State)
  {
  abbr = abbr2state(i)
  stateabb = c(stateabb,abbr)
  }

df = cbind(df,stateabb)
df$region = tolower(df$stateabb)
states = map_data("state")
statesdf = left_join(states,df, by="region")
statesdf = statesdf[order(statesdf$order),]

#Heat map showing the average ABV for each state
ggplot(statesdf, aes(x=long,y=lat,group=group))+
  geom_polygon(aes(fill=ABV))+
  geom_path()+
  ggtitle("Heap Map of Average ABV Per State")+
  scale_fill_gradientn(colours=rev(heat.colors(10)),na.value="grey90")+
  coord_map()

#The Heat Map shows the average ABV across the US so we can give suggestions to CEO's from
#evidence provided above on which states they can focus selling more IPA drinks based on high
#ABV by State.
#The top 3 states with highest average ABV would be good targets to sell more IPA's.
```
```{r}
##Conclusion
#States with highest breweries – Colorado, California and Michigan
#States with highest ABV and IBU are Colorado and Oregon
#Median alcohol content per state is fairly consistent around 6% and median international bitterness per state is very much varied.
#There is evidence to suggest that a positive linear relationship exists between IBU and ABV
#K-NN model to identify beer type based on ABV and IBU values – accuracy of 88.16%
#Target higher ABV areas to produce more IPA’s to increase sales
#Target higher ABV areas for new IPA product launches
#Top 3: Texas, South Carolina, Virginia
```





